[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_resetmethod = nodemcu
board_build.flash_mode = dout
board_build.partitions = huge_app.csv
; Upload flags for stability
upload_flags = 
    --no-stub
    --before=default_reset
    --after=hard_reset

lib_deps = 
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.17
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
  
